version: 'test-{build}'
environment:
  matrix:
    - nodejs_version: '12'
    - nodejs_version: '14'
    - nodejs_version: '16'
platform:
  - x86
  - x64
clone_folder: 'c:\projects\%APPVEYOR_PROJECT_NAME%'
install:
  - ps: 'Install-Product node $env:nodejs_version $env:platform'
  - ps: '$NpmVersion = (npm -v).Substring(0,1)'
  - ps: 'if($NpmVersion -eq 5) { npm install -g npm@5 }'
  - ps: npm --version
  - 'appveyor DownloadFile https://github.com/Apollon77/SupportingFiles/raw/master/appveyor/bonjour/bonjourcore2.msi'
  - msiexec /i bonjourcore2.msi /qn
  - del bonjourcore2.msi
  - 'appveyor DownloadFile https://github.com/Apollon77/SupportingFiles/raw/master/appveyor/bonjour/bonjoursdksetup.exe'
  - bonjoursdksetup.exe /quiet
  - del bonjoursdksetup.exe
  - 'set BONJOUR_SDK_HOME=C:\Program Files\Bonjour SDK'
  - npm install
  - npm install winston@3.2.1
  - 'npm install https://github.com/ioBroker/ioBroker.js-controller/tarball/master --production'
test_script:
  - echo %cd%
  - node --version
  - npm --version
  - npm test
build: 'off'
